### PR TITLE
Add missing API methods

### PR DESCRIPTION
**Pull request by p3ngu19z**
[API reference](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/shadowbox/server/api.yml#tag/Server/paths/~1server/get)

### CODE REVIEW

**Comment by p3ngu19z** [comment]
Environment variables names has been changed, please update it in pipeline

**Comment by jadolg** [comment]
> Environment variables has been changed, please update it in pipeline

the credentials are parsed from the installation logs on the CI [here](https://github.com/jadolg/outline-vpn-api/blob/fdb5bdb1839fc0acf2b639ecde5ca91b18fb6076/.github/workflows/test.yml#L22)

**Comment by p3ngu19z** [comment]
> > Environment variables has been changed, please update it in pipeline
> 
> the credentials are parsed from the installation logs on the CI [here](https://github.com/jadolg/outline-vpn-api/blob/fdb5bdb1839fc0acf2b639ecde5ca91b18fb6076/.github/workflows/test.yml#L22)
Can you edit this, because I'm not strong in using "sed"?

**Comment by jadolg** [comment]
It's already deployed to pypi :smiley: 
Thanks for contributing :rocket:

**Pull request merged**
